### ISSUE TITLE
Campañas - Carga

### ISSUE THREAD

**Issue by grmsuarez** [ocarriles/m2v#13]
El sistema debería tener el menú: Campañas
Allí  el cliente podrá

1. Cargar nombre de campaña.
2. Obtener un código HTML para cargar en sus piezas de HTML
3. Obtener reportes de todos los "contactos" que están cargados en el sistema y su comportamiento

**Comment by ocarriles** [comment]
Se incorporo la logica de campaña, transaccion, sesion

**Comment by ocarriles** [comment]
Parcialmente implementado

**Comment by ocarriles** [comment]
Ready
