### ISSUE TITLE
WTC - Web to Call

### ISSUE THREAD

**Issue by grmsuarez** [ocarriles/m2v#14]
El sistema debería tener en el Menú.  Web to Call
En este apartado el cliente puede

1. Crear un nombre para su landing page. 
2. El sistema arroja un código para colocar en el Title de la landing
3. Se visualiza un botón flotante de WTC
4. Hay reportes de impresiones y clicks y si los contactos están cargados en el sistema los vincula.

**Comment by ocarriles** [comment]
Se libero el primer prototipo de landing con WTC embebidos
en [este link](https://cloud.eolos.la/m2vc2c)

**Comment by ocarriles** [comment]
Ready
