### ISSUE TITLE
Llamando usando móviles

### ISSUE THREAD

**Issue by grmsuarez** [ocarriles/m2v#6]
Ayer probamos entre dos móviles con conexiones diferentes.
Funcionó ok. Hay problemas con el sonido. No ringuea

**Comment by ocarriles** [comment]
@grmsuarez 
El problema puede estar ligado a issue #3
debo verificarlo

**Comment by ocarriles** [comment]
por favor feedback sobre este issue

**Comment by ocarriles** [comment]
Parece solucionado en las nuevas versiones de chrome y safari

**Comment by ocarriles** [comment]
Ready
